[package]
name = "lake-health"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

deltalake = { version = "0.29", features = ["deltalake-aws", "deltalake-azure"] }
deltalake-azure = "0.12"
deltalake-aws = "0.12"
iceberg = { version = "0.7.0", features = ["storage-all"] }
lance = "0.39"
lance-core = "0.39"
lance-io = "0.39"

object_store = { version = "0.12", features = ["aws", "azure", "gcp"] }
url = "2.5"
async-trait = "0.1"
thiserror = "2.0"
futures = { version = "0.3", features = ["std"] }
bytes = "1.0"
chrono = "0.4"
log = "0.4.28"
regex = "1.12.2"
arrow = "56"
arrow-array = "56"
arrow-schema = "56"
parquet = "56"
uuid = { version = "1.0", features = ["v4"] }




